In [1]:
#crea una matrici 5x5 che viene riempita casualmente
#con numeri interi tra 1 e 9
import random
print("Esercizio 1")
matrix = [[random.randint(1, 9) for _ in range(5)] for _ in range(5)]
for row in matrix:
    print(row)
print()

Esercizio 1
[9, 9, 7, 3, 6]
[2, 1, 7, 9, 6]
[9, 4, 6, 9, 7]
[6, 5, 8, 5, 5]
[2, 1, 1, 3, 4]



In [2]:
#crea una matrice 4x4 riempita casualmente con 0 e 1. 
#conta quanti 1 e 0 ci sono
print("Esercizio 2")
mat4 = [[random.randint(0, 1) for _ in range(5)] for _ in range(5)]
counter0 = 0
counter1 = 0
for i in range(len(mat4)):
    for j in range(len(mat4[i])):
        if mat4[i][j] == 0:
            counter0 += 1
        else:
            counter1 += 1

for row in mat4:
    print(row)
print("Il numero 0 compare:", counter0, "volte")
print("Il numero 1 compare:", counter1, "volte")

print()

Esercizio 2
[0, 1, 0, 1, 1]
[0, 1, 1, 0, 0]
[0, 1, 0, 0, 1]
[0, 1, 0, 1, 0]
[1, 0, 0, 0, 0]
Il numero 0 compare: 15 volte
Il numero 1 compare: 10 volte



In [3]:
#crea una matrice 4x4 casualmente con numeri interi 
#tra 1 e 10 e calcola la somma di ogni riga e di ogni col
import numpy as np
print("Esercizio 3")
matrice = np.random.randint(1, 11, (4, 4))
print(matrice)
somma_righe = np.sum(matrice, axis=1)
somma_colonne = np.sum(matrice, axis=0)
print("Somma delle righe:", somma_righe)
print("Somma delle colonne:", somma_colonne)
print()

Esercizio 3
[[10 10  2  4]
 [ 4  2  6  3]
 [ 4  3  7  1]
 [ 7 10  3  5]]
Somma delle righe: [26 15 15 25]
Somma delle colonne: [25 25 18 13]



In [4]:
#crea una matrice quadrata 4x4 e stampa solo gli elementi
#sulla diagonale principale 
print("Esecizio 4")
square = np.random.randint(0, 11, (4, 4))
print(square)
diagonale = np.diag(matrice)
print("\nDiagonale principale della matrice:", diagonale)
print()

Esecizio 4
[[ 3  6 10  1]
 [ 5  8  0  3]
 [ 2  3  0  7]
 [ 0  2  8  5]]

Diagonale principale della matrice: [10  2  7  5]



In [5]:
#crea una matrice 3x3 interi casuali tra 1 e 10
#calcola la matrice trasposta (che ha scambiate righe e colonne)
print("Esercizio 5")
matrix = np.random.randint(1, 11, (3, 3))
print(matrix)
matrix_transpose = matrix.T
print("\nMatrice trasposta:")
print(matrix_transpose)
print()

Esercizio 5
[[ 8  4 10]
 [ 3 10  7]
 [ 7  2  4]]

Matrice trasposta:
[[ 8  3  7]
 [ 4 10  2]
 [10  7  4]]



In [6]:
#crea due matrici 2x2 interi 1 e 10 
#calcola il prodototto delle due matrici
print("Esercizio 6:")
matrix_a = np.random.randint(1, 11, (2, 2))
matrix_b = np.random.randint(1, 11, (2, 2))
print("Matrice A:")
print(matrix_a)
print("Matrice B:")
print(matrix_b)
prodotto = np.dot(matrix_a, matrix_b)
print("\nProdotto delle matrici A e B:")
print(prodotto)
print()

Esercizio 6:
Matrice A:
[[3 6]
 [6 2]]
Matrice B:
[[3 7]
 [5 5]]

Prodotto delle matrici A e B:
[[39 51]
 [28 52]]



In [7]:
#somma due matrici 3x3
print("Esercizio 7:")
matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))
print("Matrice A:")
print(matrix1)
print("Matrice B:")
print(matrix2)
somma = matrix1 + matrix2
print("\nSomma delle matrici A e B:")
print(somma)
print()

Esercizio 7:
Matrice A:
[[9 2 5]
 [1 3 6]
 [7 1 2]]
Matrice B:
[[4 2 6]
 [4 8 6]
 [7 5 5]]

Somma delle matrici A e B:
[[13  4 11]
 [ 5 11 12]
 [14  6  7]]



In [8]:
#crea una matrice 4x4 con numeri interi casuali tra 1 e 20
#chiedi all'utente di inserire un numero e verifica se quel
#numero è presente nella matrice
print("Esercizio 8:")
matrix = np.random.randint(1, 21, (4, 4))
print(matrix)
guess = input("Inserisci un numero: ")
try:
    guess = int(guess) 
    if np.isin(guess, matrix):
        print("Sì, eccolo")
        posizioni = np.where(matrix == guess)
        lista_posizioni = list(zip(posizioni[0], posizioni[1]))
        print("Alle seguenti coordinate:")
        for posizione in lista_posizioni:
            print(f"Riga: {posizione[0] + 1}, Colonna: {posizione[1] + 1}")
    else:
        print("Non c'è il numero che cerchi")
except ValueError:
    print("Il numero non è un numero")

Esercizio 8:
[[ 3 10  6 18]
 [16 20  3 13]
 [11  5 14 15]
 [10  7 14  8]]
Sì, eccolo
Alle seguenti coordinate:
Riga: 1, Colonna: 1
Riga: 2, Colonna: 3


In [9]:
import numpy as np
import random
S = np.random.randn(5,5)
S2 = np.zeros((5,5))
print("Matrice con random:\n", S)
print("Matrice con tutti 0:\n", S2)

Matrice con random:
 [[ 0.69457461 -0.04416067 -2.63667567 -0.13260054  0.35458473]
 [-1.39603617  1.97305492 -1.70552096  1.44459804  0.68697025]
 [-1.62356787 -1.82544675  1.10620305  0.90310142  1.25981354]
 [-1.40780367  1.15484647 -1.3658458   0.44881523  0.87409743]
 [-1.93636642 -0.58629063 -0.04003189  0.39699092 -0.41552532]]
Matrice con tutti 0:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
#con lista
matrice = [[0 for _ in range(5)]for _ in range(5)]
print("Matrice usando liste:")
for riga in matrice:
    print(riga)

matrice2 = [[np.random.randn() for _ in range(5)]for _ in range(5)]
print("Matrice casuale usando le liste:")
for riga in matrice2:
    print(riga)

Matrice usando liste:
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
Matrice casuale usando le liste:
[1.267587147350232, -0.34679076817764004, -0.8670410618553378, 0.23706214983123483, 1.7455221130902059]
[0.1961494102449602, 1.8516204092353579, -1.039482615282201, -0.2494287171703108, 2.1480696905286645]
[0.6969126518865936, 0.5059464532870767, -0.31280528656775985, 0.49966046059931635, 0.07502699516754509]
[0.7527606181897374, -0.062435989176307036, -0.42673032469177447, -0.11652010136035296, 1.049144395782041]
[-0.1421933229359929, 0.09866771130226994, 0.4505846442683187, -0.4172853973747718, 0.0026520927422843854]


In [11]:
print("Matrice 10x10: ")
matrix = np.random.randint(0, 2, (10, 10))
griglia = []


for i in range(len(matrix)):
    row = []
    for j in range(len(matrix[i])):
        if matrix[i][j] == 1:
            row.append("*")
        else:
            row.append("-")
    griglia.append(row)
        
print(matrix)
print("Initial state:")

def print_matrix(matrix):
    for row in matrix:
        print(" ".join(row))


def dead_or_alive(matrix, i, j, size_n=10):
    upper_k = i - 1 if i > 0 else 0
    lower_k = i + 1 if i < size_n - 1 else size_n - 1
    upper_l = j - 1 if j > 0 else 0
    lower_l = j + 1 if j < size_n - 1 else size_n - 1

    alive_neighbors = 0
    for k in range(upper_k, lower_k + 1):
        for l in range(upper_l, lower_l + 1):
            if (k, l) != (i, j):
                alive_neighbors += matrix[k][l]

    if matrix[i][j] == 1:
        if alive_neighbors < 2 or alive_neighbors > 3:
            return 0
        else:
            return 1
    else:
        if alive_neighbors == 3:
            return 1
    return 0


def play_game_of_life_step(matrix, size_n=10):
    new_matrix = np.zeros((size_n, size_n), dtype=int)
    for i in range(size_n):
        for j in range(size_n):
            new_matrix[i][j] = dead_or_alive(matrix, i, j, size_n)
    return new_matrix


for gen_id in range(1, 11):
    print(f'Generation {gen_id}')
    matrix = play_game_of_life_step(matrix, 10)
    print_matrix([["*" if cell == 1 else "-" for cell in row] for row in matrix])

Matrice 10x10: 
[[0 1 1 0 0 0 0 1 0 0]
 [0 0 1 1 1 0 1 1 0 0]
 [1 0 0 0 1 1 0 1 1 1]
 [1 0 0 1 0 1 0 0 1 0]
 [1 0 1 1 1 0 0 0 0 0]
 [0 1 0 1 0 1 0 1 1 0]
 [0 1 1 0 1 1 0 1 0 0]
 [0 1 0 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 1 1]
 [1 1 0 0 0 0 0 0 0 0]]
Initial state:
Generation 1
- * * - - - * * - -
- - * - * - - - - -
- * * - - - - - - *
* - * - - * * * * *
* - - - - * * * * -
* - - - - * - * * -
* * - - - * - - - -
- * - * * * * - - *
* * * - - - - - * *
- - - - - - - - - -
Generation 2
- * * * - - - - - -
- - - - - - - - - -
- - * - - * * * - *
* - * - - * - - - *
* - - - * - - - - -
* - - - * * - - * -
* * * - - - - * * -
- - - * * * * - * *
* * * * * * - - * *
- * - - - - - - - -
Generation 3
- - * - - - - - - -
- * - * - - * - - -
- * - - - * * - * -
- - - * * * - - * -
* - - * * - - - - -
* - - * * * - * * -
* * * - - - - - - -
- - - - - - * - - -
* * - - - - * * * *
* * - * * - - - - -
Generation 4
- - * - - - - - - -
- * - - - * * * - -
- - - * - - * - - -
- - * * - - * * - -
- - * 